Updated linode-cli.rb due to broken references
Brew install failing due to broken references. Example error:

```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "linode-cli--CPAN::Meta::YAML"
Download failed: http://www.cpan.org/authors/id/D/DA/DAGOLDEN/CPAN-Meta-YAML-0.012.tar.gz
```

Updated references to versions that are currently available to download.